### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: FragmentManager return a newState 1

### ISSUE THREAD

**Issue by apolalca** [adripol94/Android#5]
**FragmentManager** don't create a Fragment cause `newState > Fragment.CREATED = false` but it should be `true` is not because is not more than 1 (value of Fragment.CREATED)

Exception:
```Java
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: es.iesnervion.ejercicio52, PID: 7432
                  java.lang.IllegalArgumentException: No view found for id 0x7f0c0098 (es.iesnervion.ejercicio52:id/fragment_descriptions) for fragment DescriptionFragment{8f04b31 #4 id=0x7f0c0098}
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1107)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7224)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by apolalca** [comment]
This problem appears with last update: 70d71ff1e01cefc78e69fa4017638b4a3ddeb600

**Comment by apolalca** [comment]
Maybe it can be because the view is not **inflated**

http://stackoverflow.com/questions/18940192/no-view-found-for-id-0x7f090005
